import { NextResponse } from 'next/server';

// Country data structure
interface Country {
  name: string;
  code: string;
  native: string;
  englishName?: string;
}

// List of countries with native names and English translations where needed
const countries: Country[] = [
    { code: 'AF', name: 'Afghanistan', native: 'افغانستان', englishName: 'Afghanistan' },
    { code: 'AL', name: 'Albania', native: 'Shqipëria', englishName: 'Albania' },
    { code: 'DZ', name: 'Algeria', native: 'الجزائر', englishName: 'Algeria' },
    { code: 'AD', name: 'Andorra', native: 'Andorra' },
    { code: 'AO', name: 'Angola', native: 'Angola' },
    { code: 'AG', name: 'Antigua and Barbuda', native: 'Antigua and Barbuda' },
    { code: 'AR', name: 'Argentina', native: 'Argentina' },
    { code: 'AM', name: 'Armenia', native: 'Հայաստան', englishName: 'Armenia' },
    { code: 'AU', name: 'Australia', native: 'Australia' },
    { code: 'AT', name: 'Austria', native: 'Österreich', englishName: 'Austria' },
    { code: 'AZ', name: 'Azerbaijan', native: 'Azərbaycan', englishName: 'Azerbaijan' },
    { code: 'BS', name: 'Bahamas', native: 'Bahamas' },
    { code: 'BH', name: 'Bahrain', native: 'البحرين', englishName: 'Bahrain' },
    { code: 'BD', name: 'Bangladesh', native: 'বাংলাদেশ', englishName: 'Bangladesh' },
    { code: 'BB', name: 'Barbados', native: 'Barbados' },
    { code: 'BY', name: 'Belarus', native: 'Беларусь', englishName: 'Belarus' },
    { code: 'BE', name: 'Belgium', native: 'België/Belgique', englishName: 'Belgium' },
    { code: 'BZ', name: 'Belize', native: 'Belize' },
    { code: 'BJ', name: 'Benin', native: 'Bénin', englishName: 'Benin' },
    { code: 'BT', name: 'Bhutan', native: 'འབྲུག་ཡུལ', englishName: 'Bhutan' },
    { code: 'BO', name: 'Bolivia', native: 'Bolivia' },
    { code: 'BA', name: 'Bosnia and Herzegovina', native: 'Bosna i Hercegovina', englishName: 'Bosnia and Herzegovina' },
    { code: 'BW', name: 'Botswana', native: 'Botswana' },
    { code: 'BR', name: 'Brazil', native: 'Brasil', englishName: 'Brazil' },
    { code: 'BN', name: 'Brunei', native: 'Brunei' },
    { code: 'BG', name: 'Bulgaria', native: 'България', englishName: 'Bulgaria' },
    { code: 'BF', name: 'Burkina Faso', native: 'Burkina Faso' },
    { code: 'BI', name: 'Burundi', native: 'Burundi' },
    { code: 'KH', name: 'Cambodia', native: 'កម្ពុជា', englishName: 'Cambodia' },
    { code: 'CM', name: 'Cameroon', native: 'Cameroun', englishName: 'Cameroon' },
    { code: 'CA', name: 'Canada', native: 'Canada' },
    { code: 'CV', name: 'Cape Verde', native: 'Cabo Verde', englishName: 'Cape Verde' },
    { code: 'CF', name: 'Central African Republic', native: 'République Centrafricaine', englishName: 'Central African Republic' },
    { code: 'TD', name: 'Chad', native: 'Tchad', englishName: 'Chad' },
    { code: 'CL', name: 'Chile', native: 'Chile' },
    { code: 'CN', name: 'China', native: '中国', englishName: 'China' },
    { code: 'CO', name: 'Colombia', native: 'Colombia' },
    { code: 'KM', name: 'Comoros', native: 'جزر القمر', englishName: 'Comoros' },
    { code: 'CG', name: 'Congo', native: 'Congo' },
    { code: 'CD', name: 'Congo, Democratic Republic', native: 'République Démocratique du Congo', englishName: 'Congo, Democratic Republic' },
    { code: 'CR', name: 'Costa Rica', native: 'Costa Rica' },
    { code: 'CI', name: 'Côte d\'Ivoire', native: 'Côte d\'Ivoire' },
    { code: 'HR', name: 'Croatia', native: 'Hrvatska', englishName: 'Croatia' },
    { code: 'CU', name: 'Cuba', native: 'Cuba' },
    { code: 'CY', name: 'Cyprus', native: 'Κύπρος', englishName: 'Cyprus' },
    { code: 'CZ', name: 'Czech Republic', native: 'Česká republika', englishName: 'Czech Republic' },
    { code: 'DK', name: 'Denmark', native: 'Danmark', englishName: 'Denmark' },
    { code: 'DJ', name: 'Djibouti', native: 'جيبوتي', englishName: 'Djibouti' },
    { code: 'DM', name: 'Dominica', native: 'Dominica' },
    { code: 'DO', name: 'Dominican Republic', native: 'República Dominicana', englishName: 'Dominican Republic' },
    { code: 'EC', name: 'Ecuador', native: 'Ecuador' },
    { code: 'EG', name: 'Egypt', native: 'مصر', englishName: 'Egypt' },
    { code: 'SV', name: 'El Salvador', native: 'El Salvador' },
    { code: 'GQ', name: 'Equatorial Guinea', native: 'Guinea Ecuatorial', englishName: 'Equatorial Guinea' },
    { code: 'ER', name: 'Eritrea', native: 'ኤርትራ', englishName: 'Eritrea' },
    { code: 'EE', name: 'Estonia', native: 'Eesti', englishName: 'Estonia' },
    { code: 'ET', name: 'Ethiopia', native: 'ኢትዮጵያ', englishName: 'Ethiopia' },
    { code: 'FJ', name: 'Fiji', native: 'Fiji' },
    { code: 'FI', name: 'Finland', native: 'Suomi', englishName: 'Finland' },
    { code: 'FR', name: 'France', native: 'France' },
    { code: 'GA', name: 'Gabon', native: 'Gabon' },
    { code: 'GM', name: 'Gambia', native: 'Gambia' },
    { code: 'GE', name: 'Georgia', native: 'საქართველო', englishName: 'Georgia' },
    { code: 'DE', name: 'Germany', native: 'Deutschland', englishName: 'Germany' },
    { code: 'GH', name: 'Ghana', native: 'Ghana' },
    { code: 'GR', name: 'Greece', native: 'Ελλάδα', englishName: 'Greece' },
    { code: 'GD', name: 'Grenada', native: 'Grenada' },
    { code: 'GT', name: 'Guatemala', native: 'Guatemala' },
    { code: 'GN', name: 'Guinea', native: 'Guinée', englishName: 'Guinea' },
    { code: 'GW', name: 'Guinea-Bissau', native: 'Guiné-Bissau', englishName: 'Guinea-Bissau' },
    { code: 'GY', name: 'Guyana', native: 'Guyana' },
    { code: 'HT', name: 'Haiti', native: 'Haïti', englishName: 'Haiti' },
    { code: 'HN', name: 'Honduras', native: 'Honduras' },
    { code: 'HU', name: 'Hungary', native: 'Magyarország', englishName: 'Hungary' },
    { code: 'IS', name: 'Iceland', native: 'Ísland', englishName: 'Iceland' },
    { code: 'IN', name: 'India', native: 'भारत', englishName: 'India' },
    { code: 'ID', name: 'Indonesia', native: 'Indonesia' },
    { code: 'IR', name: 'Iran', native: 'ایران', englishName: 'Iran' },
    { code: 'IQ', name: 'Iraq', native: 'العراق', englishName: 'Iraq' },
    { code: 'IE', name: 'Ireland', native: 'Éire', englishName: 'Ireland' },
    { code: 'IL', name: 'Israel', native: 'ישראל', englishName: 'Israel' },
    { code: 'IT', name: 'Italy', native: 'Italia' },
    { code: 'JM', name: 'Jamaica', native: 'Jamaica' },
    { code: 'JP', name: 'Japan', native: '日本', englishName: 'Japan' },
    { code: 'JO', name: 'Jordan', native: 'الأردن', englishName: 'Jordan' },
    { code: 'KZ', name: 'Kazakhstan', native: 'Қазақстан', englishName: 'Kazakhstan' },
    { code: 'KE', name: 'Kenya', native: 'Kenya' },
    { code: 'KI', name: 'Kiribati', native: 'Kiribati' },
    { code: 'KP', name: 'North Korea', native: '조선민주주의인민공화국', englishName: 'North Korea' },
    { code: 'KR', name: 'South Korea', native: '대한민국', englishName: 'South Korea' },
    { code: 'KW', name: 'Kuwait', native: 'الكويت', englishName: 'Kuwait' },
    { code: 'KG', name: 'Kyrgyzstan', native: 'Кыргызстан', englishName: 'Kyrgyzstan' },
    { code: 'LA', name: 'Laos', native: 'ລາວ', englishName: 'Laos' },
    { code: 'LV', name: 'Latvia', native: 'Latvija', englishName: 'Latvia' },
    { code: 'LB', name: 'Lebanon', native: 'لبنان', englishName: 'Lebanon' },
    { code: 'LS', name: 'Lesotho', native: 'Lesotho' },
    { code: 'LR', name: 'Liberia', native: 'Liberia' },
    { code: 'LY', name: 'Libya', native: 'ليبيا', englishName: 'Libya' },
    { code: 'LI', name: 'Liechtenstein', native: 'Liechtenstein' },
    { code: 'LT', name: 'Lithuania', native: 'Lietuva', englishName: 'Lithuania' },
    { code: 'LU', name: 'Luxembourg', native: 'Luxembourg' },
    { code: 'MK', name: 'North Macedonia', native: 'Северна Македонија', englishName: 'North Macedonia' },
    { code: 'MG', name: 'Madagascar', native: 'Madagascar' },
    { code: 'MW', name: 'Malawi', native: 'Malawi' },
    { code: 'MY', name: 'Malaysia', native: 'Malaysia' },
    { code: 'MV', name: 'Maldives', native: 'ދިވެހިރާއްޖެ', englishName: 'Maldives' },
    { code: 'ML', name: 'Mali', native: 'Mali' },
    { code: 'MT', name: 'Malta', native: 'Malta' },
    { code: 'MH', name: 'Marshall Islands', native: 'Marshall Islands' },
    { code: 'MR', name: 'Mauritania', native: 'موريتانيا', englishName: 'Mauritania' },
    { code: 'MU', name: 'Mauritius', native: 'Mauritius' },
    { code: 'MX', name: 'Mexico', native: 'México', englishName: 'Mexico' },
    { code: 'FM', name: 'Micronesia', native: 'Micronesia' },
    { code: 'MD', name: 'Moldova', native: 'Moldova' },
    { code: 'MC', name: 'Monaco', native: 'Monaco' },
    { code: 'MN', name: 'Mongolia', native: 'Монгол улс', englishName: 'Mongolia' },
    { code: 'ME', name: 'Montenegro', native: 'Црна Гора', englishName: 'Montenegro' },
    { code: 'MA', name: 'Morocco', native: 'المغرب', englishName: 'Morocco' },
    { code: 'MZ', name: 'Mozambique', native: 'Moçambique', englishName: 'Mozambique' },
    { code: 'MM', name: 'Myanmar', native: 'မြန်မာ', englishName: 'Myanmar' },
    { code: 'NA', name: 'Namibia', native: 'Namibia' },
    { code: 'NR', name: 'Nauru', native: 'Nauru' },
    { code: 'NP', name: 'Nepal', native: 'नेपाल', englishName: 'Nepal' },
    { code: 'NL', name: 'Netherlands', native: 'Nederland', englishName: 'Netherlands' },
    { code: 'NZ', name: 'New Zealand', native: 'New Zealand' },
    { code: 'NI', name: 'Nicaragua', native: 'Nicaragua' },
    { code: 'NE', name: 'Niger', native: 'Niger' },
    { code: 'NG', name: 'Nigeria', native: 'Nigeria' },
    { code: 'NO', name: 'Norway', native: 'Norge', englishName: 'Norway' },
    { code: 'OM', name: 'Oman', native: 'عمان', englishName: 'Oman' },
    { code: 'PK', name: 'Pakistan', native: 'پاکستان', englishName: 'Pakistan' },
    { code: 'PW', name: 'Palau', native: 'Palau' },
    { code: 'PA', name: 'Panama', native: 'Panamá', englishName: 'Panama' },
    { code: 'PG', name: 'Papua New Guinea', native: 'Papua New Guinea' },
    { code: 'PY', name: 'Paraguay', native: 'Paraguay' },
    { code: 'PE', name: 'Peru', native: 'Perú', englishName: 'Peru' },
    { code: 'PH', name: 'Philippines', native: 'Pilipinas', englishName: 'Philippines' },
    { code: 'PL', name: 'Poland', native: 'Polska', englishName: 'Poland' },
    { code: 'PT', name: 'Portugal', native: 'Portugal' },
    { code: 'QA', name: 'Qatar', native: 'قطر', englishName: 'Qatar' },
    { code: 'RO', name: 'Romania', native: 'România', englishName: 'Romania' },
    { code: 'RU', name: 'Russia', native: 'Россия', englishName: 'Russia' },
    { code: 'RW', name: 'Rwanda', native: 'Rwanda' },
    { code: 'KN', name: 'Saint Kitts and Nevis', native: 'Saint Kitts and Nevis' },
    { code: 'LC', name: 'Saint Lucia', native: 'Saint Lucia' },
    { code: 'VC', name: 'Saint Vincent and the Grenadines', native: 'Saint Vincent and the Grenadines' },
    { code: 'WS', name: 'Samoa', native: 'Samoa' },
    { code: 'SM', name: 'San Marino', native: 'San Marino' },
    { code: 'ST', name: 'Sao Tome and Principe', native: 'São Tomé e Príncipe', englishName: 'Sao Tome and Principe' },
    { code: 'SA', name: 'Saudi Arabia', native: 'المملكة العربية السعودية', englishName: 'Saudi Arabia' },
    { code: 'SN', name: 'Senegal', native: 'Sénégal', englishName: 'Senegal' },
    { code: 'RS', name: 'Serbia', native: 'Србија', englishName: 'Serbia' },
    { code: 'SC', name: 'Seychelles', native: 'Seychelles' },
    { code: 'SL', name: 'Sierra Leone', native: 'Sierra Leone' },
    { code: 'SG', name: 'Singapore', native: 'Singapore' },
    { code: 'SK', name: 'Slovakia', native: 'Slovensko', englishName: 'Slovakia' },
    { code: 'SI', name: 'Slovenia', native: 'Slovenija', englishName: 'Slovenia' },
    { code: 'SB', name: 'Solomon Islands', native: 'Solomon Islands' },
    { code: 'SO', name: 'Somalia', native: 'Soomaaliya', englishName: 'Somalia' },
    { code: 'ZA', name: 'South Africa', native: 'South Africa' },
    { code: 'SS', name: 'South Sudan', native: 'South Sudan' },
    { code: 'ES', name: 'Spain', native: 'España', englishName: 'Spain' },
    { code: 'LK', name: 'Sri Lanka', native: 'ශ්‍රී ලංකාව', englishName: 'Sri Lanka' },
    { code: 'SD', name: 'Sudan', native: 'السودان', englishName: 'Sudan' },
    { code: 'SR', name: 'Suriname', native: 'Suriname' },
    { code: 'SZ', name: 'Eswatini', native: 'Eswatini' },
    { code: 'SE', name: 'Sweden', native: 'Sverige', englishName: 'Sweden' },
    { code: 'CH', name: 'Switzerland', native: 'Schweiz/Suisse/Svizzera', englishName: 'Switzerland' },
    { code: 'SY', name: 'Syria', native: 'سوريا', englishName: 'Syria' },
    { code: 'TW', name: 'Taiwan', native: '台灣', englishName: 'Taiwan' },
    { code: 'TJ', name: 'Tajikistan', native: 'Тоҷикистон', englishName: 'Tajikistan' },
    { code: 'TZ', name: 'Tanzania', native: 'Tanzania' },
    { code: 'TH', name: 'Thailand', native: 'ประเทศไทย', englishName: 'Thailand' },
    { code: 'TL', name: 'Timor-Leste', native: 'Timor-Leste' },
    { code: 'TG', name: 'Togo', native: 'Togo' },
    { code: 'TO', name: 'Tonga', native: 'Tonga' },
    { code: 'TT', name: 'Trinidad and Tobago', native: 'Trinidad and Tobago' },
    { code: 'TN', name: 'Tunisia', native: 'تونس', englishName: 'Tunisia' },
    { code: 'TR', name: 'Turkey', native: 'Türkiye', englishName: 'Turkey' },
    { code: 'TM', name: 'Turkmenistan', native: 'Türkmenistan', englishName: 'Turkmenistan' },
    { code: 'TV', name: 'Tuvalu', native: 'Tuvalu' },
    { code: 'UG', name: 'Uganda', native: 'Uganda' },
    { code: 'UA', name: 'Ukraine', native: 'Україна', englishName: 'Ukraine' },
    { code: 'AE', name: 'United Arab Emirates', native: 'الإمارات العربية المتحدة', englishName: 'United Arab Emirates' },
    { code: 'GB', name: 'United Kingdom', native: 'United Kingdom' },
    { code: 'US', name: 'United States', native: 'United States' },
    { code: 'UY', name: 'Uruguay', native: 'Uruguay' },
    { code: 'UZ', name: 'Uzbekistan', native: 'Ozbekiston', englishName: 'Uzbekistan' },
    { code: 'VU', name: 'Vanuatu', native: 'Vanuatu' },
    { code: 'VA', name: 'Vatican City', native: 'Città del Vaticano', englishName: 'Vatican City' },
    { code: 'VE', name: 'Venezuela', native: 'Venezuela' },
    { code: 'VN', name: 'Vietnam', native: 'Việt Nam', englishName: 'Vietnam' },
    { code: 'YE', name: 'Yemen', native: 'اليمن', englishName: 'Yemen' },
    { code: 'ZM', name: 'Zambia', native: 'Zambia' },
    { code: 'ZW', name: 'Zimbabwe', native: 'Zimbabwe' }
  ];

export async function GET() {
  try {
    console.log('🔍 Fetching countries list...');
    
    // Sort countries alphabetically by native name
    const sortedCountries = [...countries].sort((a, b) => {
      // Put Italy at the top
      if (a.code === 'IT') return -1;
      if (b.code === 'IT') return 1;
      
      return a.native.localeCompare(b.native);
    });
    
    console.log(`✅ Successfully fetched ${sortedCountries.length} countries`);
    return NextResponse.json(sortedCountries, { status: 200 });
    
  } catch (error) {
    console.error('💥 Server error:', error);
    return NextResponse.json(
      { error: 'Internal server error', details: error instanceof Error ? error.message : 'Unknown error' },
      { status: 500 }
    );
  }
}